import turtle

turtle.circle(120)
turtle.up()
turtle.forward(40)
turtle.left(90)
turtle.forward(160)
turtle.right(90)
turtle.down()
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.up()
turtle.backward(80)
turtle.down()

turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.up()
turtle.right(90)
turtle.forward(70)
turtle.left(140)
turtle.down()
turtle.forward(70)
turtle.right(100)
turtle.forward(70)

turtle.left(50)
turtle.up()
turtle.forward(30)
turtle.down()

turtle.right(140)
turtle.forward(110)
turtle.right(90)
turtle.forward(110)
turtle.done()